On many scripts: correspondent to '#'-beginning style comments in @list, @blacklist files and so on. saa-get-apps, saa-put-apps: add a -o|--overwrite option.

diff --git a/saa-copy-saadir b/saa-copy-saadir
--- a/saa-copy-saadir
+++ b/saa-copy-saadir
@@ -2,7 +2,8 @@
 pname=$(basename "$0")
 dname=$(dirname "$0")
 case "$dname" in /*);; *) dname="$(pwd)/$dname";; esac
-usage="$pname [-q|--quiet|-v|--verbose|-n|--dryrun] SourceSAADir NewSAADir
+source "$dname/saa-environ.sh"
+usage="$pname [Options] SourceSAADir NewSAADir
 $pname  {-h|--help}
 Features:
   make new SAADir (a. k. a. Sync Android Apps Directory) by copy from the
@@ -17,8 +18,6 @@ Options:
     Only messages displayed, No SAADirectory is made.
   -h|--help
     This help message is displayed."
-
-source "$dname/saa-environ.sh"
 
 quietp=false
 verbosep=false
@@ -44,13 +43,17 @@ while true; do
   done
 done
 $opterrp && exit 1
-$helpp || test $# -ne 0 && { echo "$usage"; exit;}
-test $# -ne 2 && { echo "$pname: missing arguments.">&2; exit 1;}
+$helpp && { echo "$usage"; exit;}
+test $# -ne 2 && { echo "$pname: Requires two arguments.">&2; exit 1;}
 $verbosep && {
   quietp=false
   lnopt=--verbose
 }
 
+
+testwildf() {
+  test -f "$1"
+}
 
 saadir="$1"
 newsaadir="$2"
@@ -63,9 +66,15 @@ $quietp || echo "make $newsaadir.">&2
 mkdir -p "$newsaadir"/"$appsdir" ||
   { echo "$newsaadir/$appsdir: mkdir failed.">&2; exit 3;}
 for obj in apk ab; do
-  $quietp || echo "make hardlinks for $obj.">&2
-  ln${lnopt:+ $lnopt} "$saadir"/"$appsdir"/*.$obj "$newsaadir"/"$appsdir" ||
-    { echo "$pname: abort.">&2; exit 4;}
+  testwildf "$saadir"/"$appsdir"/*.$obj && {
+    $quietp || echo "make hardlinks for $obj.">&2
+    ln${lnopt:+ $lnopt} "$saadir"/"$appsdir"/*.$obj "$newsaadir"/"$appsdir" ||
+      {
+        echo "$pname: abort.">&2
+        rm -rf "$newsaadir"
+        exit 4
+      } 
+  }
 done
 
 (
@@ -76,6 +85,21 @@ done
   #"$dname"/saa-make-desc ||
   #  { echo "$pname: abort.">&2; exit 6; }
 )
-$quietp || echo "copy $blacklist.">&2
-cp "$saadir"/"$blacklist" "$newsaadir"/ ||
-  { echo "$pname: abort.">&2; exit 7; }
+testwildf "$saadir"/"$blacklist"* && {
+  $quietp || echo "copy blacklists.">&2
+  cp "$saadir"/"$blacklist"* "$newsaadir"/ ||
+    {
+      echo "$pname: abort.">&2
+      rm -rf "$newsaadir"
+      exit 7
+    }
+}
+testwildf "$saadir"/"$whitelist"* && {
+  $quietp || echo "copy whitelists.">&2
+  cp "$saadir"/"$whitelist"* "$newsaadir"/ ||
+    {
+      echo "$pname: abort.">&2
+      rm -rf "$newsaadir"
+      exit 8
+    }
+}
